import { DefaultHeadTags } from "./DefaultHeadTags";

export default function Head() {
  return (
    <>
      <DefaultHeadTags />
      <title>Momotabs</title>
      <meta name="description" content="Generated by create next app" />
    </>
  )
}
