import { DefaultHeadTags } from "../../DefaultHeadTags";

export default function Head(props: {
  params: { songId: string };
}) {
  const { params } = props;
  const { songId } = params;
  return (
    <>
      <DefaultHeadTags />
      <title>Momotabs - song {songId}</title>
      <meta name="description" content="Generated by create next app" />
    </>
  )
}
