import { getSong } from "../../(backend)/backend";
import { DefaultHeadTags } from "../../DefaultHeadTags";

export default async function Head(props: {
  params: { songId: string };
}) {
  const { params } = props;
  const { songId } = params;
  const song = await getSong(songId);
  const title = song === undefined ? `Song not found - Momotabs` : `${song.title} - ${song.artist} - Momotabs`
  return (
    <>
      <DefaultHeadTags />
      <title>{title}</title>
      <meta name="description" content="Generated by create next app" />
    </>
  )
}
